### ISSUE TITLE
Webpack 'babel-loader' won't transpile this library

### ISSUE THREAD

**Issue by Robzzson** [mljs/distance-matrix#1]
When I import this library like:
```javascript
const distanceMatrix = require('ml-distance-matrix');
```
and bundle my code using webpack the following error appears in the web browser: 

> TypeError: distanceMatrix is not a function

When I debug the code in a browser it turns out that the type of `distanceMatrix` is a Module:

![screen](https://user-images.githubusercontent.com/22998248/78709896-b919bd00-7914-11ea-85a2-1df03548d49c.png)

On the other hand when I test the code locally using Jest & Node everything runs fine. It indeed suggests that there is something wrong with transpiling the code. I'm wondering why is there a nested "declare" modifier in [distance-matrix.d.ts](https://github.com/mljs/distance-matrix/blob/master/distance-matrix.d.ts#L2) and why is it being used in an already ambient context? Could this be the source of the problem?

I'm working on a project, where I use a bunch of different mljs libraries and this is the only one that does not work "out of the box". I picked up JS roughly 3 months ago, so forgive me in case I'm making some dumb mistake.

**Comment by targos** [comment]
Hi. I fixed the TypeScript definition in v2.0.1 but it probably won't change your problem.
Can you try to `import distanceMatrix from 'ml-distance-matrix'` ?
Anyway, there's nothing we can do in this package. I think the "default" property is added by babel on you side (it's not in the code we publish).

**Comment by Robzzson** [comment]
It indeed does not solve my problem. After switching from 'require()' to importing the default export the way you mentioned it, now I get:
> import distanceMatrix from 'ml-distance-matrix';
    ^^^^^^
> SyntaxError: Cannot use import statement outside a module

{Named} imports that I have in other `.test.js` files work fine. Default import from `ml-distance-matrix` does not. There must be some problem with my Babel config. Thank you for your help.
